# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: CMS
  licenses: Apache-2.0
  images: |
    - name: gotrue
      image: docker.io/bitnami/gotrue:1.0.1-debian-12-r21
    - name: jwt-cli
      image: docker.io/bitnami/jwt-cli:6.0.0-debian-12-r17
    - name: kubectl
      image: docker.io/bitnami/kubectl:1.29.2-debian-12-r2
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r16
    - name: postgrest
      image: docker.io/bitnami/postgrest:11.2.2-debian-12-r12
    - name: supabase-postgres
      image: docker.io/bitnami/supabase-postgres:15.1.1-debian-12-r13
    - name: supabase-postgres-meta
      image: docker.io/bitnami/supabase-postgres-meta:0.79.0-debian-12-r0
    - name: supabase-realtime
      image: docker.io/bitnami/supabase-realtime:2.25.65-debian-12-r0
    - name: supabase-storage
      image: docker.io/bitnami/supabase-storage:0.47.0-debian-12-r3
    - name: supabase-studio
      image: docker.io/bitnami/supabase-studio:0.23.11-debian-12-r8
apiVersion: v2
appVersion: 0.23.11
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 15.x.x
- condition: kong.enabled
  name: kong
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Supabase is an open source Firebase alternative. Provides all the necessary backend features to build your application in a scalable way. Uses PostgreSQL as datastore.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/supabase/img/supabase-stack-220x234.png
keywords:
- development
- dashboards
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: supabase
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/supabase
version: 3.0.0